version: '3.9'

services:
  mysql:
    image: mysql:8
    container_name: fitcard-mysql
    volumes:
      - db:/var/lib/mysql
    restart: "no"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=root
    networks:
      - fitcard
    ports:
      - "3306:3306"
      
  backend:
    image: limgayoung/fitcard-be:latest
    container_name: fitcard-be
    depends_on:
      - mysql
    ports:
      - "8081:8081"
    restart: "always"
    networks:
      - fitcard
    
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # nginx 설정 파일 경로
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf  # 사이트 관련 설정
      - ./www:/var/www/html  # 정적 파일 제공을 위한 경로
      - /etc/letsencrypt:/etc/letsencrypt  # SSL 인증서 경로
    depends_on:
      - backend
    restart: "always"
    networks:
      - fitcard
volumes:
  db: {}

networks:
  fitcard:
    name: fitcard
    driver: bridge
